repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.2
      hooks:
          - id: ruff
            args: [--fix]
          - id: ruff-format

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.9.0
      hooks:
          - id: mypy
            additional_dependencies:
                - types-PyYAML
                - types-requests
                - types-setuptools